name: AdzzzPhotography
favicon: null
layout_spectrum: 0.25534
typography_spectrum: 0.78269
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#67766f'
    - '#dddabb'
    - '#b0bcb0'
    - '#809586'
    - '#ab3529'
  brandStrength: 0.6875
  lightness: 0.7624219062272459
  saturation: 0.875
  rhythmicContrast: 0.7985235725063831
purpose: []
